---

image: python:latest

build:
  only:
    - tags
  script:
    - pip install --upgrade build setuptools twine
    - python -m build
    # Upload to GitLab package registry
    - >-
      TWINE_PASSWORD="${CI_JOB_TOKEN}"
      TWINE_USERNAME='gitlab-ci-token'
      TWINE_REPOSITORY_URL="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi"
      python -m twine upload
      dist/*
    # Upload to PyPi
    - >-
      TWINE_PASSWORD="${PYPI_TOKEN}"
      TWINE_USERNAME='__token__'
      python -m twine upload
      dist/*
